sudo: required
services:
        - docker
before_install:
        - docker build -t needchai/test-docker -f Dockerfile.dev .
script:
        - docker run needchai/test-docker npm run test -- --coverage
