sudo: required
services:
        - docker
before_install:
        - docker build -t needchai/docker-react -f Dockerfile.dev .
script:
        - docker run needchai/docker-react npm run test -- --coverage
