sudo: required
langauge: node_js
node_js:
        - "8"
services:
        - docker
before_install:
        - docker build -t needchai/test-docker -f Dockerfile.dev .
script:
        - docker run -e CI=true needchai/test-docker npm run test -- --coverage
